"""Knowledge ingestion pipeline.

Pulls optimization knowledge from external sources into the
experience store and knowledge base:
- GPU MODE kernelbot submissions (8K+ successful solutions)
- GPU MODE KernelBook (18K PyTorch->Triton pairs)
- KernelBench leaderboard solutions
- Kernel Arena published results

Each source is ingested as structured experience records
with traits, strategies, and outcomes.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class IngestedKernel:
	"""A kernel solution from an external source."""

	source: str  # "gpumode_kernelbot", "kernelbook", "kernel_arena"
	problem_name: str
	original_code: str
	optimized_code: str
	hardware: str  # "MI300", "A100", "B200", etc.
	language: str  # "cuda", "triton", "hip", "python"
	speedup: float  # 0 if unknown
	correct: bool
	metadata: dict


def ingest_kernelbook(
	output_dir: Path,
	max_entries: int = 5000,
) -> list[IngestedKernel]:
	"""Ingest GPU MODE KernelBook: PyTorch -> Triton translation pairs.

	18K entries of PyTorch code paired with Inductor-generated Triton
	kernels. Useful as examples of what good Triton code looks like.
	"""
	from huggingface_hub import hf_hub_download

	logger.info("Downloading KernelBook dataset...")
	path = hf_hub_download(
		"GPUMODE/KernelBook",
		"dataset_permissive.parquet",
		repo_type="dataset",
	)

	import pandas as pd
	df = pd.read_parquet(path)
	logger.info("KernelBook: %d entries loaded", len(df))

	kernels: list[IngestedKernel] = []
	for _, row in df.head(max_entries).iterrows():
		python_code = str(row.get("python_code", ""))
		triton_code = str(row.get("triton_code", ""))
		entry_point = str(row.get("entry_point", "unknown"))

		if not python_code or not triton_code:
			continue

		kernels.append(IngestedKernel(
			source="kernelbook",
			problem_name=entry_point,
			original_code=python_code[:5000],
			optimized_code=triton_code[:10000],
			hardware="generic_cuda",
			language="triton",
			speedup=0.0,  # no speedup data in KernelBook
			correct=True,  # generated by Inductor
			metadata={
				"repo": str(row.get("repo_name", "")),
				"stars": int(row.get("stars", 0)),
				"synthetic": bool(row.get("synthetic", False)),
			},
		))

	# Save as JSONL
	output_dir.mkdir(parents=True, exist_ok=True)
	out_path = output_dir / "kernelbook.jsonl"
	with open(out_path, "w") as f:
		for k in kernels:
			f.write(json.dumps({
				"source": k.source,
				"problem_name": k.problem_name,
				"original_code": k.original_code,
				"optimized_code": k.optimized_code,
				"hardware": k.hardware,
				"language": k.language,
				"metadata": k.metadata,
			}) + "\n")

	logger.info(
		"Saved %d KernelBook entries to %s", len(kernels), out_path
	)
	return kernels


def ingest_kernelbot(
	output_dir: Path,
	max_entries: int = 5000,
) -> list[IngestedKernel]:
	"""Ingest GPU MODE kernelbot competition submissions.

	8K+ successful submissions across AMD MI300 and NVIDIA NVFP4
	competitions. Each has source code, pass/fail, and runtime score.
	"""
	from huggingface_hub import hf_hub_download

	logger.info("Downloading kernelbot submissions...")

	kernels: list[IngestedKernel] = []

	# AMD successful submissions
	path = hf_hub_download(
		"GPUMODE/kernelbot-data",
		"deduplicated_successful_submissions.parquet",
		repo_type="dataset",
	)
	import pandas as pd
	df = pd.read_parquet(path)
	logger.info("kernelbot AMD submissions: %d", len(df))

	for _, row in df.head(max_entries).iterrows():
		code = str(row.get("code", ""))
		if not code or len(code) < 50:
			continue

		# Detect language from code
		lang = "hip" if "hip" in code.lower() else "triton"
		if "load_inline" in code:
			lang = "hip"
		elif "@triton.jit" in code:
			lang = "triton"

		kernels.append(IngestedKernel(
			source="gpumode_kernelbot",
			problem_name=str(row.get("file_name", "unknown")),
			original_code="",  # reference not in dataset
			optimized_code=code[:10000],
			hardware="MI300",
			language=lang,
			speedup=0.0,  # score is runtime, not speedup
			correct=bool(row.get("run_passed", False)),
			metadata={
				"leaderboard_id": int(row.get("leaderboard_id", 0)),
				"run_score": str(row.get("run_score", "")),
				"submission_id": int(row.get("submission_id", 0)),
			},
		))

	# NVFP4 submissions
	try:
		path2 = hf_hub_download(
			"GPUMODE/kernelbot-data",
			"nvidia_nvfp4_submissions.parquet",
			repo_type="dataset",
		)
		nv = pd.read_parquet(path2)
		logger.info("kernelbot NVFP4 submissions: %d", len(nv))

		for _, row in nv.head(max_entries).iterrows():
			code = str(row.get("code", ""))
			if not code or len(code) < 50:
				continue

			kernels.append(IngestedKernel(
				source="gpumode_kernelbot_nvfp4",
				problem_name=str(row.get("file_name", "unknown")),
				original_code="",
				optimized_code=code[:10000],
				hardware="B200",
				language="cuda",
				speedup=0.0,
				correct=bool(row.get("run_passed", False)),
				metadata={
					"run_score": str(row.get("run_score", "")),
				},
			))
	except Exception as e:
		logger.warning("Could not load NVFP4 data: %s", e)

	# Save
	output_dir.mkdir(parents=True, exist_ok=True)
	out_path = output_dir / "kernelbot.jsonl"
	with open(out_path, "w") as f:
		for k in kernels:
			f.write(json.dumps({
				"source": k.source,
				"problem_name": k.problem_name,
				"optimized_code": k.optimized_code,
				"hardware": k.hardware,
				"language": k.language,
				"correct": k.correct,
				"metadata": k.metadata,
			}) + "\n")

	logger.info(
		"Saved %d kernelbot entries to %s", len(kernels), out_path
	)
	return kernels


def extract_patterns(
	kernels: list[IngestedKernel],
) -> list[dict]:
	"""Extract optimization patterns from ingested kernels.

	Analyzes code to identify common strategies:
	- Shared memory usage patterns
	- Vectorized load patterns
	- Triton tile sizes and configurations
	- Fusion patterns
	"""
	patterns: list[dict] = []

	# Triton patterns
	triton_kernels = [
		k for k in kernels
		if k.language == "triton" and k.optimized_code
	]

	# Extract common block sizes
	block_sizes: dict[str, int] = {}
	for k in triton_kernels:
		for match in re.finditer(
			r"BLOCK[_A-Z]*\s*[:=]\s*(\d+)", k.optimized_code
		):
			size = match.group(1)
			block_sizes[size] = block_sizes.get(size, 0) + 1

	if block_sizes:
		top_sizes = sorted(
			block_sizes.items(), key=lambda x: -x[1]
		)[:10]
		patterns.append({
			"type": "triton_block_sizes",
			"data": dict(top_sizes),
			"insight": (
				f"Most common Triton block sizes from "
				f"{len(triton_kernels)} kernels: "
				+ ", ".join(f"{s}({c})" for s, c in top_sizes[:5])
			),
		})

	# Shared memory patterns
	smem_count = sum(
		1 for k in kernels
		if "__shared__" in k.optimized_code
	)
	if smem_count > 0:
		patterns.append({
			"type": "shared_memory_usage",
			"data": {
				"count": smem_count,
				"total": len(kernels),
				"pct": round(smem_count / len(kernels) * 100, 1),
			},
			"insight": (
				f"{smem_count}/{len(kernels)} "
				f"({smem_count/len(kernels)*100:.0f}%) kernels "
				f"use shared memory"
			),
		})

	# Float4 vectorized loads
	vec_count = sum(
		1 for k in kernels
		if "float4" in k.optimized_code or "tl.load" in k.optimized_code
	)
	if vec_count:
		patterns.append({
			"type": "vectorized_loads",
			"data": {"count": vec_count, "total": len(kernels)},
			"insight": (
				f"{vec_count}/{len(kernels)} kernels use "
				f"vectorized loads"
			),
		})

	logger.info(
		"Extracted %d patterns from %d kernels",
		len(patterns), len(kernels),
	)
	return patterns


def build_triton_examples_index(
	kernelbook_path: Path,
	output_path: Path,
	max_examples_per_op: int = 3,
) -> dict:
	"""Build an index of Triton code examples by operation type.

	The agent can query this to get real Triton examples for
	specific operations (softmax, layernorm, matmul, etc.)
	"""
	if not kernelbook_path.exists():
		return {}

	index: dict[str, list[dict]] = {}
	op_patterns = {
		"matmul": ["fused_mm", "fused_bmm", "matmul", "addmm"],
		"softmax": ["softmax", "log_softmax"],
		"layernorm": ["layer_norm", "native_layer_norm"],
		"batchnorm": ["batch_norm", "native_batch_norm"],
		"attention": ["attention", "sdpa", "scaled_dot"],
		"relu": ["relu", "fused_relu"],
		"gelu": ["gelu", "fused_gelu"],
		"conv": ["conv2d", "conv1d", "convolution"],
		"reduce": ["sum", "mean", "max", "min", "prod"],
	}

	with open(kernelbook_path) as f:
		for line in f:
			entry = json.loads(line)
			name = entry.get("problem_name", "").lower()
			code = entry.get("optimized_code", "")

			for op_type, keywords in op_patterns.items():
				if any(kw in name for kw in keywords):
					if op_type not in index:
						index[op_type] = []
					if len(index[op_type]) < max_examples_per_op:
						index[op_type].append({
							"name": entry["problem_name"],
							"code": code[:3000],
						})
					break

	output_path.parent.mkdir(parents=True, exist_ok=True)
	output_path.write_text(json.dumps(index, indent=2))

	total = sum(len(v) for v in index.values())
	logger.info(
		"Built Triton examples index: %d examples across %d op types",
		total, len(index),
	)
	return index
